/** Типы для системы P2P Bluetooth-синхронизации Solo */

// Импортируем общие типы из shared
import {
  PlatformType,
  PeerDevice,
  SyncConnectionState,
  MessageType,
  HandshakePayload,
  HandshakeAckPayload,
  FileManifestEntry,
  TombstoneManifestEntry,
  ManifestPayload,
  ManifestDiffPayload,
  FilePayload,
  FileAckPayload,
  TombstonePayload,
  SyncCompletePayload,
  DisconnectPayload,
  ConflictResolutionPayload,
  ErrorPayload,
  SyncMessage,
  SyncConflict,
  SyncEventType,
  SyncEvent,
  SyncProgress,
  SyncStatus,
  SyncBridgeAPI,
} from '../shared/types';

// Экспортируем все типы и значения
export {
  PlatformType,
  PeerDevice,
  SyncConnectionState,
  MessageType,
  HandshakePayload,
  HandshakeAckPayload,
  FileManifestEntry,
  TombstoneManifestEntry,
  ManifestPayload,
  ManifestDiffPayload,
  FilePayload,
  FileAckPayload,
  TombstonePayload,
  SyncCompletePayload,
  DisconnectPayload,
  ConflictResolutionPayload,
  ErrorPayload,
  SyncMessage,
  SyncConflict,
  SyncEventType,
  SyncEvent,
  SyncProgress,
  SyncStatus,
  SyncBridgeAPI,
};
