/**
 * Типы для системы синхронизации Solo.
 * Реэкспорт из shared/types.ts
 */

import type {
  PlatformType,
  PeerDevice,
  SyncConnectionState,
  MessageType,
  HandshakePayload,
  HandshakeAckPayload,
  FileManifestEntry,
  TombstoneManifestEntry,
  ManifestPayload,
  ManifestDiffPayload,
  FilePayload,
  FileAckPayload,
  TombstonePayload,
  SyncCompletePayload,
  DisconnectPayload,
  ConflictResolutionPayload,
  ErrorPayload,
  SyncMessage,
  SyncConflict,
  SyncEventType,
  SyncEvent,
  SyncProgress,
  SyncStatus,
  SyncBridgeAPI,
  SyncMode,
  WebDAVConfig,
  RemoteDeviceSnapshot,
  ISyncTransport,
} from '../shared/types';

// Экспортируем типы (с isolatedModules требуется export type)
export type {
  PlatformType,
  SyncMode,
  PeerDevice,
  SyncConnectionState,
  MessageType,
  HandshakePayload,
  HandshakeAckPayload,
  FileManifestEntry,
  TombstoneManifestEntry,
  ManifestPayload,
  ManifestDiffPayload,
  FilePayload,
  FileAckPayload,
  TombstonePayload,
  SyncCompletePayload,
  DisconnectPayload,
  ConflictResolutionPayload,
  ErrorPayload,
  SyncMessage,
  SyncConflict,
  SyncEventType,
  SyncEvent,
  SyncProgress,
  SyncStatus,
  SyncBridgeAPI,
  WebDAVConfig,
  RemoteDeviceSnapshot,
  ISyncTransport,
};
