import { ElectronAPI, FileMetadata, FileNode } from '../types';
import { structure as contentStructure, loadContent } from 'virtual:solo-content';

/**
 * In-memory file store for packaged (web) builds.
 *
 * The note tree comes from the `--content <folder>` build flag: the
 * {@link contentStructure} (generated by the `solo-content` Vite plugin) provides
 * the folder/file hierarchy plus metadata, while the note HTML is fetched lazily
 * via {@link loadContent} the first time a note is opened.
 *
 * Notes can still be created, edited, renamed and deleted entirely in memory.
 */

// ── File content storage (path → HTML string) ──
// Holds notes created/edited in memory as well as lazily loaded note contents.
const fileContents = new Map<string, string>();

// ── Metadata storage (path → FileMetadata) ──
const metadatas = new Map<string, FileMetadata>();

// ── Live tree used by readStructure(); mutated by create/rename/delete ops. ──
let structure: FileNode[] = [];

// ── Paths of notes whose content can be lazily loaded from the content bundle. ──
const lazyPaths = new Set<string>();

let idCounter = 0;

function nextId(): string {
  return `mem-${++idCounter}-${Date.now()}`;
}

/** Generate a unique .html path within a parent folder */
function makeHtmlPath(parentPath: string, title: string): string {
  const safeName = title.replace(/[/\\?%*:|"<>]/g, '_').slice(0, 100);
  const fileName = `${safeName} - ${Date.now()}.html`;
  return parentPath ? `${parentPath}/${fileName}` : fileName;
}

// ── Seed demo content (used only when no --content folder was supplied) ──
function seedDemoFiles() {
  const demoFiles: Array<{ path: string; content: string }> = [
    {
      path: 'inbox/Быстрая заметка.html',
      content: '<p>Это пример быстрой заметки.</p>',
    },
    {
      path: 'inbox/Идея для проекта.html',
      content: '<p>Идеи для проекта:</p><ul><li>Идея 1</li><li>Идея 2</li></ul>',
    },
    {
      path: 'projects/Solo/Архитектура.html',
      content: '<h1>Архитектура Solo</h1><p>Описание архитектуры приложения.</p>',
    },
    {
      path: 'projects/Solo/Заметки по UI.html',
      content: '<h1>UI заметки</h1><p>Размышления о дизайне интерфейса.</p>',
    },
    {
      path: 'projects/Digikam Companion/Требования.html',
      content: '<h1>Требования</h1><p>Список требований к приложению.</p>',
    },
    {
      path: 'diary/2025-06-23 Запись.html',
      content: '<p>Дневниковая запись за 23 июня 2025 года.</p>',
    },
    {
      path: 'references/Полезные ссылки.html',
      content: '<p>Полезные ссылки и ресурсы.</p>',
    },
  ];

  for (const { path, content } of demoFiles) {
    if (!fileContents.has(path)) {
      fileContents.set(path, content);
    }
  }
}

/** Static demo tree structure – used only when no --content folder was supplied */
function buildStaticStructure(): FileNode[] {
  return [
    {
      name: 'Входящие',
      path: 'inbox',
      type: 'folder',
      children: [
        {
          name: 'Быстрая заметка.html',
          path: 'inbox/Быстрая заметка.html',
          type: 'file',
          metadata: {
            id: 'inbox-01',
            tags: ['входящие'],
            createdAt: '2025-01-15T10:30:00Z',
            theme: '',
            paragraphTags: ['p1', 'p2'],
          },
        },
        {
          name: 'Идея для проекта.html',
          path: 'inbox/Идея для проекта.html',
          type: 'file',
          metadata: {
            id: 'inbox-02',
            tags: ['входящие', 'идеи'],
            createdAt: '2025-02-03T14:15:00Z',
            theme: '',
            paragraphTags: ['p1'],
          },
        },
      ],
    },
    {
      name: 'Проекты',
      path: 'projects',
      type: 'folder',
      children: [
        {
          name: 'Solo',
          path: 'projects/Solo',
          type: 'folder',
          children: [
            {
              name: 'Архитектура.html',
              path: 'projects/Solo/Архитектура.html',
              type: 'file',
              metadata: {
                id: 'proj-solo-01',
                tags: ['solo', 'архитектура'],
                createdAt: '2025-03-01T09:00:00Z',
                theme: '',
                paragraphTags: ['p1', 'p2', 'p3'],
              },
            },
            {
              name: 'Заметки по UI.html',
              path: 'projects/Solo/Заметки по UI.html',
              type: 'file',
              metadata: {
                id: 'proj-solo-02',
                tags: ['solo', 'ui'],
                createdAt: '2025-03-10T11:45:00Z',
                theme: '',
                paragraphTags: ['p1'],
              },
            },
          ],
        },
        {
          name: 'Digikam Companion',
          path: 'projects/Digikam Companion',
          type: 'folder',
          children: [
            {
              name: 'Требования.html',
              path: 'projects/Digikam Companion/Требования.html',
              type: 'file',
              metadata: {
                id: 'proj-digikam-01',
                tags: ['digikam', 'spec'],
                createdAt: '2025-04-20T16:30:00Z',
                theme: '',
                paragraphTags: ['p1', 'p2'],
              },
            },
          ],
        },
      ],
    },
    {
      name: 'Дневник',
      path: 'diary',
      type: 'folder',
      children: [
        {
          name: '2025-06-23 Запись.html',
          path: 'diary/2025-06-23 Запись.html',
          type: 'file',
          metadata: {
            id: 'diary-01',
            tags: ['дневник'],
            createdAt: '2025-06-23T20:00:00Z',
            theme: '',
            paragraphTags: ['p1', 'p2', 'p3', 'p4'],
          },
        },
      ],
    },
    {
      name: 'Справочное',
      path: 'references',
      type: 'folder',
      children: [
        {
          name: 'Полезные ссылки.html',
          path: 'references/Полезные ссылки.html',
          type: 'file',
          metadata: {
            id: 'ref-01',
            tags: ['reference', 'links'],
            createdAt: '2025-05-12T08:00:00Z',
            theme: '',
            paragraphTags: ['p1'],
          },
        },
      ],
    },
  ];
}

/** Deep clone a FileNode tree so runtime mutations don't touch the build-time data. */
function cloneStructure(nodes: FileNode[]): FileNode[] {
  return nodes.map((node) => ({
    ...node,
    metadata: node.metadata ? { ...node.metadata } : undefined,
    children: node.children ? cloneStructure(node.children) : undefined,
  }));
}

/** Walk a tree registering metadata and, for content-backed notes, lazy paths. */
function indexTree(nodes: FileNode[], lazy: boolean) {
  for (const node of nodes) {
    if (node.type === 'folder') {
      if (node.children) indexTree(node.children, lazy);
      continue;
    }
    if (node.metadata) {
      metadatas.set(node.path, node.metadata);
    }
    if (lazy && node.path.endsWith('.html')) {
      lazyPaths.add(node.path);
    }
  }
}

// ── Initialise the store from the content bundle (or demo fallback). ──
function initStore() {
  if (contentStructure && contentStructure.length > 0) {
    structure = cloneStructure(contentStructure);
    indexTree(structure, true);
  } else {
    seedDemoFiles();
    structure = buildStaticStructure();
    indexTree(structure, false);
  }
}

initStore();

/** Read a note's content, lazily loading it from the content bundle if needed. */
async function readContent(relativePath: string): Promise<string | undefined> {
  if (fileContents.has(relativePath)) {
    return fileContents.get(relativePath);
  }
  if (lazyPaths.has(relativePath)) {
    const content = await loadContent(relativePath);
    if (content !== null && content !== undefined) {
      fileContents.set(relativePath, content);
      return content;
    }
  }
  return undefined;
}

// ── Tree mutation helpers (operate on the live `structure`) ──

function findParentList(targetPath: string): FileNode[] {
  const parentPath = targetPath.includes('/')
    ? targetPath.slice(0, targetPath.lastIndexOf('/'))
    : '';
  if (!parentPath) return structure;

  let current: FileNode[] = structure;
  const segments = parentPath.split('/');
  let acc = '';
  for (const segment of segments) {
    acc = acc ? `${acc}/${segment}` : segment;
    const folder = current.find((n) => n.path === acc && n.type === 'folder');
    if (!folder) return structure;
    if (!folder.children) folder.children = [];
    current = folder.children;
  }
  return current;
}

function removeNode(targetPath: string): FileNode | undefined {
  const list = findParentList(targetPath);
  const idx = list.findIndex((n) => n.path === targetPath);
  if (idx === -1) return undefined;
  return list.splice(idx, 1)[0];
}

function rebasePaths(node: FileNode, oldBase: string, newBase: string) {
  node.path = node.path === oldBase ? newBase : newBase + node.path.slice(oldBase.length);
  if (node.children) {
    for (const child of node.children) rebasePaths(child, oldBase, newBase);
  }
}

/** Create a stub ElectronAPI that works fully in memory for packaged web builds. */
export function createStubAPI(): ElectronAPI {
  const stub: {
    [K in keyof ElectronAPI]: (...args: any[]) => Promise<any>;
  } = {
    // ── Folder / file operations (not available, but return gracefully) ──
    selectFolder: async () => {
      return { success: false, error: 'Not available in packaged build' };
    },
    getDataFolder: async () => {
      return { success: false, error: 'Not available in packaged build' };
    },
    selectParentFolder: async () => {
      return { success: false, error: 'Not available in packaged build' };
    },

    // ── In-memory read / write (with lazy content loading) ──
    openFile: async (relativePath: string) => {
      const content = await readContent(relativePath);
      if (content === undefined) {
        return { success: false, error: `File "${relativePath}" not found in memory` };
      }
      return { success: true, content };
    },
    updateFile: async (relativePath: string, content: string) => {
      fileContents.set(relativePath, content);
      return { success: true };
    },
    updateMetadata: async (relativePath: string, metadata: FileMetadata) => {
      metadatas.set(relativePath, metadata);
      return { success: true };
    },
    readStructure: async () => {
      return { success: true, structure };
    },

    // ── Tag scanning ──
    scanAllTags: async () => {
      const tags = new Set<string>();
      for (const meta of metadatas.values()) {
        meta.tags?.forEach((tag) => tags.add(tag));
        meta.paragraphTags?.forEach((tag) => tags.add(tag));
      }
      return { success: true, tags: Array.from(tags).sort() };
    },

    // ── Zen mode ──
    toggleZenMode: async () => {
      return { success: false, error: 'Not available in packaged build' };
    },
    getZenMode: async () => {
      return { success: true, isZenMode: false };
    },

    // ── Search (in-memory, lazily loads content when needed) ──
    search: async (searchString?: string, tags?: string[]) => {
      const results: Array<{ path: string; type: string; matches: string[]; metadata?: FileMetadata }> = [];
      const hasSearchString = searchString && searchString.trim().length > 0;
      const hasTags = tags && tags.length > 0;

      if (!hasSearchString && !hasTags) {
        return { success: true, results: [] };
      }

      const searchLower = searchString?.toLowerCase() || '';

      // Collect all known note paths from content store, metadata and lazy paths.
      const allPaths = new Set([
        ...fileContents.keys(),
        ...metadatas.keys(),
        ...lazyPaths,
      ]);

      for (const filePath of allPaths) {
        const matches: string[] = [];
        const meta = metadatas.get(filePath);
        const fileName = filePath.split('/').pop() || filePath;

        // ── Filename match ──
        if (hasSearchString && fileName.toLowerCase().includes(searchLower)) {
          matches.push('filename');
        }

        // ── Content match (HTML notes only) ──
        if (hasSearchString && filePath.endsWith('.html')) {
          const content = await readContent(filePath);
          if (content && content.toLowerCase().includes(searchLower)) {
            matches.push('content');
          }
        }

        // ── Metadata / tag matching ──
        if (meta) {
          if (hasTags && meta.tags) {
            const hasMatchingTag = tags!.some(tag =>
              meta.tags!.some(metaTag =>
                metaTag.toLowerCase().includes(tag.toLowerCase())
              )
            );
            if (hasMatchingTag) {
              matches.push('metadata:tags');
            }
          }

          if (hasSearchString) {
            if (meta.id?.toLowerCase().includes(searchLower)) {
              matches.push('metadata:id');
            }
            if (meta.tags?.some(tag => tag.toLowerCase().includes(searchLower))) {
              matches.push('metadata:tags');
            }
          }
        }

        if (matches.length > 0) {
          results.push({
            path: filePath,
            type: matches.includes('content') ? 'content' : 'filename',
            matches: [...new Set(matches)],
            metadata: meta,
          });
        }
      }

      return { success: true, results };
    },

    // ── Notebooks (in-memory) ──
    createNotebook: async (parentPath: string, name: string) => {
      const path = parentPath ? `${parentPath}/${name}` : name;
      const list = findParentList(path);
      if (!list.some((n) => n.path === path)) {
        list.push({ name, path, type: 'folder', children: [] });
      }
      return { success: true, path };
    },
    deleteNotebook: async (relativePath: string) => {
      removeNode(relativePath);
      return { success: true };
    },
    renameNotebook: async (relativePath: string, newName: string) => {
      const parts = relativePath.split('/');
      parts[parts.length - 1] = newName;
      const newPath = parts.join('/');
      const list = findParentList(relativePath);
      const node = list.find((n) => n.path === relativePath);
      if (node) {
        node.name = newName;
        rebasePaths(node, relativePath, newPath);
      }
      return { success: true, newPath };
    },

    // ── Notes (in-memory) ──
    createNote: async (parentPath: string, name: string) => {
      const id = nextId();
      const htmlPath = makeHtmlPath(parentPath, name);
      const now = new Date().toISOString();
      const metadata: FileMetadata = {
        id,
        tags: [],
        createdAt: now,
        theme: '',
        paragraphTags: [],
      };
      fileContents.set(htmlPath, '');
      metadatas.set(htmlPath, metadata);
      const list = findParentList(htmlPath);
      list.push({
        name: htmlPath.split('/').pop() || htmlPath,
        path: htmlPath,
        type: 'file',
        metadata,
      });
      return { success: true, htmlPath, id };
    },
    deleteNote: async (relativePath: string) => {
      fileContents.delete(relativePath);
      metadatas.delete(relativePath);
      lazyPaths.delete(relativePath);
      removeNode(relativePath);
      return { success: true };
    },
    renameNote: async (relativePath: string, newName: string) => {
      const parts = relativePath.split('/');
      const ext = parts[parts.length - 1].includes('.') ? '.' + parts[parts.length - 1].split('.').pop() : '.html';
      parts[parts.length - 1] = newName.replace(/[^a-zA-Zа-яА-Я0-9 _-]/g, '') + ext;
      const newPath = parts.join('/');

      // Ensure content is materialised before moving (in case it was lazy).
      const content = await readContent(relativePath);
      const meta = metadatas.get(relativePath);
      if (content !== undefined) {
        fileContents.set(newPath, content);
        fileContents.delete(relativePath);
      }
      if (meta) {
        metadatas.set(newPath, meta);
        metadatas.delete(relativePath);
      }
      lazyPaths.delete(relativePath);

      const list = findParentList(relativePath);
      const node = list.find((n) => n.path === relativePath);
      if (node) {
        node.name = newPath.split('/').pop() || newPath;
        node.path = newPath;
      }
      return { success: true, newPath };
    },

    // ── PDF ──
    openPdfFile: async () => {
      return { success: false, error: 'Not available in packaged build' };
    },

    // ── File picker ──
    selectFile: async () => {
      return { success: false, error: 'Not available in packaged build' };
    },

    // ── Digikam ──
    getDigikamTags: async () => {
      return { success: false, error: 'Not available in packaged build' };
    },
    getDigikamImagesByTag: async () => {
      return { success: false, error: 'Not available in packaged build', digikamTag: '' };
    },
  };
  return stub as unknown as ElectronAPI;
}
